stages:
  load_data:
    cmd: python src/load_data.py --config=config/params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - Dataset/spam_or_not_spam.csv
    outs:
    - data/raw/spam_or_not_spam.csv


  split_data:
      cmd: python src/split_data.py --config=config/params.yaml
      deps:
      - src/split_data.py
      - data/raw/x_array.csv.npy
      - data/raw/y_array.csv.npy
      outs:
      - data/processed/x_train_spam_or_not_spam.csv.npy
      - data/processed/x_test_spam_or_not_spam.csv.npy
      - data/processed/y_train_spam_or_not_spam.csv.npy
      - data/processed/y_test_spam_or_not_spam.csv.npy

  train_and_evaluate:
      cmd: python src/train_evaluate.py --config=config/params.yaml
      deps:
      - data/processed/x_train_spam_or_not_spam.csv.npy
      - data/processed/x_test_spam_or_not_spam.csv.npy
      - data/processed/y_train_spam_or_not_spam.csv.npy
      - data/processed/y_test_spam_or_not_spam.csv.npy 
      - src/train_evaluate.py
      # metrics:
      # - reports/scores.json:
      #     cache: false

  # log_production_model:
  #     cmd: python src/train_evaluate.py --config=config/params.yaml
  #     deps:
  #     - src/log_production_model.py

